### ISSUE TITLE
Bot not list his commands in command pallete

### ISSUE THREAD

**Issue by Akiyamka** [Rulexec/shieldy#3]
![изображение](https://user-images.githubusercontent.com/6587585/141682203-49304513-24d5-4b39-ac5c-7e751e8ed512.png)

**Comment by Akiyamka** [comment]
according to official [docs](https://core.telegram.org/api/bots/commands) we have two ways:
- use api [bots.setBotCommands](https://core.telegram.org/method/bots.setBotCommands)
- use [@botfather](https://t.me/botfather) and command [/setcommands](https://stackoverflow.com/a/34458436)

**Comment by Rulexec** [comment]
Implemented, thanks 👍

https://t.me/sesuritu_news/2
